# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.replicate.audio.enhance
from nodetool.workflows.base_node import BaseNode


class AudioSuperResolution(
    SingleOutputGraphNode[types.AudioRef], GraphNode[types.AudioRef]
):
    """
    AudioSR: Versatile Audio Super-resolution at Scale
    """

    seed: int | OutputHandle[int] | None = connect_field(
        default=None, description="Random seed. Leave blank to randomize the seed"
    )
    ddim_steps: int | OutputHandle[int] = connect_field(
        default=50, description="Number of inference steps"
    )
    input_file: types.AudioRef | OutputHandle[types.AudioRef] = connect_field(
        default=types.AudioRef(
            type="audio", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Audio to upsample",
    )
    guidance_scale: float | OutputHandle[float] = connect_field(
        default=3.5, description="Scale for classifier free guidance"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.replicate.audio.enhance.AudioSuperResolution

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
