# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.replicate.image.ocr
from nodetool.workflows.base_node import BaseNode


class LatexOCR(SingleOutputGraphNode[str], GraphNode[str]):
    """
    Optical character recognition to turn images of latex equations into latex format.
    """

    image_path: str | OutputHandle[str] | None = connect_field(
        default=None, description="Input image"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.replicate.image.ocr.LatexOCR

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.replicate.image.ocr
from nodetool.workflows.base_node import BaseNode


class TextExtractOCR(SingleOutputGraphNode[str], GraphNode[str]):
    """
    A simple OCR Model that can easily extract text from an image.
    """

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Image to process",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.replicate.image.ocr.TextExtractOCR

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
