# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.replicate.video.enhance
from nodetool.workflows.base_node import BaseNode


class Runway_Upscale_V1(
    SingleOutputGraphNode[types.VideoRef], GraphNode[types.VideoRef]
):
    """
    Upscale videos by 4x, up to a maximum of 4k
    """

    video: types.VideoRef | OutputHandle[types.VideoRef] = connect_field(
        default=types.VideoRef(
            type="video",
            uri="",
            asset_id=None,
            data=None,
            metadata=None,
            duration=None,
            format=None,
        ),
        description="Video to upscale. Videos must be shorter than 40s, less than 4096px per side, and less than 16MB.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.replicate.video.enhance.Runway_Upscale_V1

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.replicate.video.enhance
from nodetool.workflows.base_node import BaseNode


class Topaz_Video_Upscale(
    SingleOutputGraphNode[types.VideoRef], GraphNode[types.VideoRef]
):
    """
    Video Upscaling from Topaz Labs
    """

    Target_resolution: typing.ClassVar[type] = (
        nodetool.nodes.replicate.video.enhance.Topaz_Video_Upscale.Target_resolution
    )

    video: types.VideoRef | OutputHandle[types.VideoRef] = connect_field(
        default=types.VideoRef(
            type="video",
            uri="",
            asset_id=None,
            data=None,
            metadata=None,
            duration=None,
            format=None,
        ),
        description="Video file to upscale",
    )
    target_fps: int | OutputHandle[int] = connect_field(
        default=60, description="Target FPS (choose from 15fps to 120fps)"
    )
    target_resolution: (
        nodetool.nodes.replicate.video.enhance.Topaz_Video_Upscale.Target_resolution
    ) = Field(
        default=nodetool.nodes.replicate.video.enhance.Topaz_Video_Upscale.Target_resolution(
            "1080p"
        ),
        description="Target resolution",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.replicate.video.enhance.Topaz_Video_Upscale

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
